name: 'Terraform Metric Aggregator'
description: 'An experimental action that analyses static Terraform code and builds a report'
author: 'Off Grid Development'

inputs:
  github_token:
    description: GitHub token
  working_directory:
    description: target directory for analysis
  event:
    description: this event
  includedFileTypes:
    description: RegExp pattern for files to include in report
  excludedFileTypes:
    description: RegExp pattern for files to exclude from report

# Define your outputs here.
outputs:
  export_filename:
    description: the path to the report produced

runs:
  using: node20
  main: dist/index.js
